name: rds2h5ad
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # ---- Python stack ----
  - python=3.10
  - scanpy
  - anndata
  - pip
  - pip:
      - pyreadr
      - rpy2

  # ---- R stack ----
  - r-base=4.2
  - r-essentials             # includes IRkernel
  - r-seurat=5.*             # Seurat itself
  - r-seurat-disk            # SeuratDisk
  - r-hdf5r                  # HDF5 bindings
  - r-r.utils                # for gunzip if needed
