name: rds2h5ad
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python stack
  - python=3.10
  - scanpy
  - anndata
  - pip
  - pip:
    - pyreadr
    - rpy2

  # R stack (with IRkernel for Jupyter)
  - r-base=4.2
  - r-essentials        # brings in IRkernel + core R packages
  - bioconductor-seurat=5.3
  - bioconductor-seurat-disk
  - hdf5
  - hdf5r
  - r-r.utils
