name: rds2h5ad
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python stack
  - python=3.10
  - scanpy
  - anndata
  - pip
  - pip:
      - pyreadr
      - rpy2

  # R stack (ensuring compatibility)
  - r-base=4.4
  - r-essentials
  - r-seurat
  - r-seurat-disk
  - r-hdf5r
  - r-r.utils
